<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IJ" nsURI="http://ij" nsPrefix="ij">
  <eClassifiers xsi:type="ecore:EClass" name="I">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="js" upperBound="-1" eType="#//J"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="J">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="j" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is" upperBound="-1" eType="#//I"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="js" upperBound="-1" eType="#//J"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
